/*
 * Copyright 2021 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/*  global document */

async function getPaths() {
  // TODO get from index ?
  return [
    '/en/publish/09/03/delivering-equitable-and-inclusive-digital-services-with-adobe-solutions',
    '/en/publish/09/03/announcing-c2pa-draft-specification',
    '/en/publish/09/03/master-documentary-storytelling-for-marketing',
    '/en/publish/09/03/how-dcps-supports-students-social-and-emotional-health-through-art',
    '/en/publish/09/03/announcing-winners-2021-adobe-government-creativity-awards',
    '/en/publish/09/02/max-2021-luminary-speakers',
    '/en/publish/09/02/introducing-the-2021-adobe-community-advisors',
    '/en/publish/09/02/api-creativity',
    '/en/publish/09/02/power-of-digital-self-sufficiency-why-its-time-brands-have-technology-fluency2',
    '/en/publish/09/02/carve-out-more-time-small-business-owner-with-adobe-acrobat-online',
    '/en/publish/09/02/dishing-up-visually-delicious-animation-for-netflixs-waffles-mochi',
    '/en/publish/09/02/bolster-your-business-operations-with-video-content',
    '/en/publish/09/02/a-perpetual-series-of-hope-betting-big-and-fishing-with-chris-raimondi-of-tabcorp',
    '/en/publish/09/02/top-5-reasons-to-join-the-adobe-experience-league-government-community',
    '/en/publish/09/20/how-keep-everyone-on-same-page-for-community-projects',
    '/en/publish/09/20/adobe-announces-major-milestone-adoption-ai-powered-capabilities-adobe-experience-cloud',
    '/en/publish/09/20/esperanza-celebration-of-hispanic-heritage',
    '/en/publish/09/20/nvidia-studio-supercharges-creative-workflows-adobe-max-2021',
    '/en/publish/09/20/adobe-india-created-impactful-virtual-internship',
    '/en/publish/09/20/building-a-strong-foundation-for-security-and-governance-with-digital-document-processes',
    '/en/publish/09/20/adobe-announces-major-milestone-in-the-adoption-of-ai-powered-capabilities-in-adobe-experience-cloud-uk',
    '/en/publish/09/20/adobe-digital-economy-index-flight-prices-fall-as-covid-19-dampens-demand-thanksgiving-bookings-off-to-slow-start',
    '/en/publish/09/20/adobe-max-2021-creativity-design-in-business',
    '/en/publish/09/27/adobe-leader-2021-gartner-mq-b2b-marketing-automation-platforms',
    '/en/publish/09/27/leveraging-ai-as-an-opportunity-for-strategic-business-transformation',
    '/en/publish/09/27/connect-with-others-visually-a-pre-max-experience',
    '/en/publish/09/29/equipping-the-next-generation-with-creative-skills-and-digital-literacy',
    '/en/publish/09/29/a-love-song-for-hispanic-heritage-month',
    '/en/publish/09/29/adobe-named-top-company-for-working-parents',
    '/en/publish/09/29/shell-philippines-fuels-dealer-partnerships-with-adobe-sign',
    '/en/publish/09/16/how-adobe-university-program-helped-accelerate-learning',
    '/en/publish/09/16/agata-szyler-seidl-sea-site-lead-access-at-adobe',
    '/en/publish/09/16/what-is-content-democratization-and-how-is-it-changing-the-business-landscape',
    '/en/publish/09/16/4-data-driven-tips-for-holiday-ecommerce-success',
    '/en/publish/09/16/video-content-creation-the-future-of-influencer-marketing',
    '/en/publish/09/16/forecasting-new-digital-standard-us-census-with-illuminator-christina-stoehr',
    '/en/publish/09/16/how-people-and-purpose-shaped-adelinas-career',
    '/en/publish/09/28/navitas-opens-up-new-possibilities-for-students-with-adobe-experience-cloud',
    '/en/publish/09/28/from-the-acr-team-masking-reimagined',
    '/en/publish/09/28/adorn-cosmetics-gives-its-e-commerce-experience-a-makeover-with-adobe-commerce',
    '/en/publish/09/28/better-films-no-burnout-producing-better-videos-faster',
    '/en/publish/09/17/dive-into-ui-ux-design-at-adobe-max',
    '/en/publish/09/17/down-the-blue-bayou-with-editor-reynolds-barney',
    '/en/publish/09/17/blending-fact-fiction-in-ifc-films-the-nowhere-inn',
    '/en/publish/09/17/register-opt-in-by-october-15-for-chance-win-max-t-shirt',
    '/en/publish/09/17/headless-can-build-allies-among-marketing-and-technology-teams',
    '/en/publish/09/10/from-mops-practitioner-to-manager-its-all-about-mindset-for-jessica-kao',
    '/en/publish/09/10/study-better-smarter-and-faster-with-adobe-acrobat',
    '/en/publish/09/10/creativity-as-self-care-how-photography-can-boost-your-wellness-practices',
    '/en/publish/09/21/world-interaction-design-day-2021',
    '/en/publish/09/21/creative-workflow-photographer-aundre-larrows-ritual-and-process',
    '/en/publish/09/21/adobe-max-2021-education-track',
    '/en/publish/09/21/exploring-importance-adobe-creative-cloud-in-stem-fields',
    '/en/publish/09/21/how-emotional-intelligence-is-unlocking-the-power-of-customer-insight',
    '/en/publish/09/21/everything-comes-down-cdp-the-rapid-rise-customer-data-platform',
    '/en/publish/09/21/how-successfully-acquire-create-manage-important-documents-for-your-freelance-business',
    '/en/publish/09/07/adobe-named-a-leader-in-the-2021-gartner-magic-quadrant-for-digital-commerce',
    '/en/publish/09/07/keep-important-documents-on-hand-anywhere-you-go-with-adobe-acrobat-online',
    '/en/publish/09/07/answering-your-questions-adobe-frameio',
    '/en/publish/09/07/how-to-improve-sustainability-in-schools',
    '/en/publish/09/07/adobe-max-2021-video-track',
    '/en/publish/09/09/integrating-low-lift-high-impact-digital-teaching-learning-practices-in-college-classrooms',
    '/en/publish/09/09/seeking-the-stories-histories-and-values-behind-food-in-stock-imagery',
    '/en/publish/09/09/discover-the-future-of-3d-ar-at-adobe-max',
    '/en/publish/09/30/the-future-looks-bright-for-marketing-creative-job-seekers',
    '/en/publish/09/30/creating-the-future-with-our-interns',
    '/en/publish/09/30/goaltending-teamwork-trust-emeas-experience-maker-of-the-year-klaus-fiedel',
    '/en/publish/09/08/video-content-consumption-how-gen-z-and-millennials-have-changed-the-game',
    '/en/publish/09/08/act-like-a-video-creator-think-like-a-digital-marketer',
    '/en/publish/09/01/8-ways-to-preserve-your-childs-memories-and-keepsakes',
    '/en/publish/09/01/ford-digital-first-approach-put-customers-in-driving-seat-during-lockdown',
    '/en/publish/09/01/the-path-to-personalization-maturity',
    '/en/publish/09/01/livestream-fails-what-to-learn-from-others-mistakes',
    '/en/publish/09/01/adobe-named-to-people-magazines-companies-that-care-for-the-fifth-year',
    '/en/publish/09/01/photography-track-at-adobe-max-2021',
    '/en/publish/09/24/better-customer-experiences-for-all-reimagining-digital-engagement-with-adobe-experience-cloud',
    '/en/publish/09/24/sustainable-ux-design-what-is-it-and-how-can-it-benefit-your-organization',
    '/en/publish/09/24/the-future-of-hr-human-resource-trends-on-the-rise',
    '/en/publish/09/23/how-to-pursue-past-due-invoices-politely-and-effectively',
    '/en/publish/09/23/7-types-of-digital-documents-your-small-business-needs',
    '/en/publish/09/23/clifford-chance-bringing-the-legal-industry-into-the-twenty-first-century',
    '/en/publish/09/23/adobe-launches-the-uk-creative-council-with-riz-ahmed-to-inspire-creativity-for-all',
    '/en/publish/09/23/adobe-x-qai-qai-coloring-book-encouraging-young-girls-explore-their-limitless-potential',
    '/en/publish/09/23/supercharge-your-workflow-with-adobe-wrike',
    '/en/publish/09/23/using-power-creativity-for-vaccine-education',
    '/en/publish/09/15/adobe-for-all-do-one-thing-today',
    '/en/publish/09/15/adobe-digital-economy-index-ecommerce-hits-new-milestone-online-prices-continue-rise',
    '/en/publish/09/15/bringing-a-childhood-vision-to-life',
    '/en/publish/09/15/setting-your-out-of-office-for-adobe-max',
    '/en/publish/09/15/the-future-of-retail-in-a-cookie-free-world',
    '/en/publish/09/15/purpose-value-cultural-rehabilitation-buildings-neighborhoods-through-art',
    '/en/publish/09/15/digital-commerce-leaders-face-uncertainty-this-holiday-season',
    '/en/publish/09/13/learning-new-ways-of-thinking-software-engineer-intern',
    '/en/publish/09/13/adobe-named-to-nine-constellation-research-shortlist-categories-for-digital-transformation-technologies',
    '/en/publish/09/13/10-ways-to-keep-kids-engaged-while-you-work-from-home',
    '/en/publish/09/14/gaining-invaluable-skills-for-the-future',
    '/en/publish/09/14/adobe-stock-motion-trend-eye-catching-transformative-transitions',
    '/en/publish/09/14/unlocking-business-growth-with-customer-journey-management',
    '/en/publish/09/14/recapture-the-magic-of-hybrid-design-workshops-with-miro-and-adobe',
    '/en/publish/09/14/how-lot-improved-its-customer-journey-created-additional-revenue-stream-using-digital-marketing-technology',
    '/en/publish/09/14/using-data-for-outcome-focused-creative-team-management',
    '/en/publish/09/14/volvo-cars-drives-modern-service-through-adobe-sign',
    '/en/publish/09/14/presenting-adobe-stock-artist-development-fund-recipients-group-three',
    '/en/publish/09/22/level-up-with-professional-certifications-for-adobe-creative-cloud',
    '/en/publish/09/22/overcoming-the-boardroom-barriers-to-digital-transformation',
    '/en/publish/09/22/how-to-apply-for-a-small-business-loan',
    '/en/publish/09/22/tomorrows-cmo-to-shake-up-marketing-teams',
    '/en/publish/09/22/9-sales-strategies-to-close-a-business-deal-faster',
    '/en/publish/09/22/suzanne-bourdeaux-career-pivots-tips-charting-your-path',
    '/en/publish/09/22/become-a-character-anime-tor-new-free-anime-style-puppets',
    '/en/publish/09/22/tips-every-freelancer-should-consider-for-vetting-clients',
  ];
}

export {
  getPaths,
};
